### ISSUE TITLE
[1.18.2] Packets not being handled upon player trying to use enchantment table. Crashes.

### ISSUE THREAD

**Issue by ConqAra** [IlMusu/IlMusuEnchantmentsMod#26]
It seems like when one of my players tried to interact with the enchantment table, it failed to load the packet. then upon any of gui opening (inventory, etc.) it could not be opened. complete packet failure. after a few seconds it would just completely crash the server. For more context, he was trying to put a fishing rod into the enchantment table. But even just opening the table would cause these issue. after removing your mod the issue seemed to fix, he could interact with the enchantment table just fine.

Error: [https://paste.ee/p/38mc7](https://paste.ee/p/38mc7)
Full Log (it's massive. very bizzare. error starts at Punderful20 saying "Imma try something"): https://paste.ee/p/3Pegm

**Comment by IlMusu** [comment]
I see where the problem occurred but it is really... bizarre.
It seems like the enchanting table could not generate enchantments for the fishing rod (which should never be the case).
I always supposed that it was possible to generate enchantments. There may be some strangeness going on with other mods. I don't know since I'm unable to reproduce the error. 
Despite that, I coded I small fix that should prevent this from happening again

**Comment by IlMusu** [comment]
Ok, I managed to exactly reproduce the error.
Apparently, when there are no bookshelves around the enchanting table this happens since the enchantments for the 3rd level are not generated. Strange Minecraft and it's shenanigans

**Comment by ConqAra** [comment]
Strangest thing is that it was fine when i interacted with it, but maybe cuz im host? i wasnt quite understanding it myself honestly.

**Comment by IlMusu** [comment]
I really have no idea about that D:

**Comment by ConqAra** [comment]
Thats okay, Im sure everything will be fixed on the new release. thank you for always being so quick to look into things!
