### ISSUE TITLE
The data of things in the pockets of pants

### ISSUE THREAD

**Issue by mrcrashmer** [IlMusu/IlMusuEnchantmentsMod#34]
First of all, thank you so much for the prompt update (Fix 33). It was fast and works great. But now I'm interested. The Switchy mod does not remember things in pockets, but it does it perfectly with backpacks, so. Where does the mod store data about things, can I change them, for example, with the command /item replace?

**Comment by IlMusu** [comment]
I would have to investigate because I'm not completely sure.
I suppose that switchy inventories uses the read and write functions of the PlayerInventory to switch the inventories. That is where all the data is stored. The backpack mod probably stores its data inside of that too and that is why it works automatically.
When developing the Pockets Enchantment I remember trying to extend the inventory but that created problems which I don't remember now... so I made the pockets be completely separate from the inventory.
The most simple solution that I can think of  (if what I supposed is right) is a hook that stores the data of the pockets into the data of the inventory, which will make everything work and should not be too difficult to implement.

I don't think there is some way of making everything work with a command....
